name: Build for production
on:
  push:
    branches:
      - staging
jobs:
  build:
    name: Try running production build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.16
      - name: Install dependencies
        run: npm install
      # - name: Lint
      #   run: npm run lint
      - name: Build
        run: npm run build --prod
